# Generated by Django 2.0 on 2017-12-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('valid_purchase', models.BooleanField(default=False)),
            ],
        ),
    ]
