# Generated by Django 2.0 on 2017-12-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('shipping_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('valid_purchase', models.BooleanField(default=False)),
                ('cart_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='server.Carts')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('cart_id', 'id')},
        ),
    ]
