# Generated by Django 2.0 on 2018-01-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('cart_id', 'item_id')},
        ),
    ]
