# Generated by Django 2.0 on 2018-01-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180110_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('cart', 'item_id')},
        ),
    ]
