# Generated by Django 2.0 on 2018-01-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180110_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cart',
            field=models.IntegerField(),
        ),
    ]
