# Generated by Django 2.0 on 2018-01-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180112_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('cart_id', 'item_id')},
        ),
    ]
