# Generated by Django 2.0 on 2018-01-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180112_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='cart_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
